app.py
from flask import Flask, render_template

from views import my_view

app = Flask(__name__)
app.register_blueprint(my_view)

@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html", e=e)

@app.errorhandler(500)
def server_down():
    return render_template("500.html")


if __name__ == "__main__":
    app.run(debug=True, port=8000)

views.py
from flask import render_template, redirect, url_for, Blueprint

my_view = Blueprint('my_view', __name__)


@my_view.route("/")
def page1():
    return render_template("index1.html")

@my_view.route("/page2")
def page2():
    return render_template("index2.html")

@my_view.route("/page3")
def page3():
    return render_template("index3.html")

@my_view.route("/page4")
def page4():
    return render_template("index4.html")

@my_view.route("/page5")
def page5():
    return render_template("index5.html")

@my_view.route("/admin_page")
def admin_page():
    return render_template("admin.html")




@my_view.route("/home")
def home_redirect():
    return redirect(url_for("my_view.page1"))

@my_view.route("/javascript")
def java_redirect():
    return redirect(url_for("my_view.page1"))

@my_view.route("/js")
def js_redirect():
    return redirect(url_for("my_view.page1"))

@my_view.route("/admin")
def admin_redirect():
    return redirect(url_for("my_view.admin_page"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename = 'main.css')}}">
    <style>@import url('https://fonts.googleapis.com/css2?family=Lobster&display=swap');</style>
    <style>@import url('https://fonts.googleapis.com/css2?family=Comfortaa:wght@500&family=Lobster&display=swap');</style>
    <title>Indie Fan</title>
</head>
<body>


<div class="banner">
    <div class="navleft">
        <div class="navleft1">
            <div class="namebutton">
                <a href="{{ url_for('my_view.page1')}}">Indie Fan</a>
            </div>
        </div>

        <div class="navleft2">
            <img class="headerpic" src="static/images/momo3.jpg">
        </div>
    </div>

    <div class="navright">
            <a href="#" id="menu" onclick="dropdown()">Menu</a>
            <div id="hidebox" class="hidden">
            <div class="button1">
            <a href="{{ url_for('my_view.page1')}}">Home</a>
            </div>
            <div class="button2">
            <a href="{{ url_for('my_view.page2')}}">Showcase</a>
            </div>
            <div class="button3">
            <a href="{{ url_for('my_view.page3')}}">Recommended</a>
            </div>
            <div class="button4">
            <a href="{{ url_for('my_view.page4')}}">Your Pick!</a>
            </div>
            <div class="button5">
            <a href="{{ url_for('my_view.page5')}}">Contact</a>
            </div></div>
    </div>
</div>


{% block content %}
{% endblock %}

<span class="desk"></span>
<span class="mobile"></span>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="./static/main.js"></script>

</body>
</html>

templates/index1.html
{% extends 'base.html' %}
{% block content %}

<div class="headingblock">
    <div class="headingleftbox">
        <h4>Home</h4>
    </div>
    <div class="headingmidbox">
        <h4>Home</h4>
    </div>
    <div class="headingrightbox">
        <h4>Home</h4>
    </div>
</div>

<div class="stage">
    <div class="stage2">
        <div class="stage3">
            <div class="mainbox">
                <div class="contentblock">
                    <div class="contentblocka">
                        <div class="carbox">
                            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                </div>
                                <div class="carousel-inner">
                                <div class="carousel-item active" data-bs-interval="6000" style="background-image: url(static/images/axiomface.jpg)">
                                    <img src="static/images/axiomface.jpg" class="d-block w-100" alt="axiomface">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5>Axiom Verge</h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/isaacbackg.jpg)">
                                    <img src="static/images/isaacbackg.jpg" class="d-block w-100" alt="isaacbackground">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5>Isaac: Repentence</h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/osboat.jpg)">
                                    <img src="static/images/osboat.jpg" class="d-block w-100" alt="oneshot">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5>OneShot</h5>
                                    <p></p>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="contentblockb">
                        <p class="para"><br>Welcome to Indie Fan! Your bite-sized chunk of indipendant goodness. We love small games because more often than not, what you see is what you get. And if you know what you like, there's plenty on offer to keep you satisfied. No micro-transactions, no overblown hype trains, no drama.<br><br>Are you looking for unfiltered creativity, original ideas, beautiful art and great mechanics? We've got you covered right here! Please visit our contact page where you can enter polls to have your favourite indie games showcased.</p>
                    </div>
                </div>

                <div class="contentblock2">
                    <div class="contentblock2a">
                            <img class="lowerpic1" src="static/images/tsbannermic.png">
                    </div>
                    <div class="contentblock2b">
                        <p class="para"><br>This week.<br>We showcase an absolute gem. Oneshot. It's atmospheric, it's impactful and it gets meta in ways we never expected. You don't want to miss out on this experience.<br>We look at an updated classic with The Binding of Isaac:Repentence. New overhauls, new items and new difficulty?<br>Last but not least, we present your pick of the week. Retro stlye, good story, nice visuals and bangin music? Yep. All developed by one man? Yes!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/index2.html
{% extends 'base.html' %}
{% block content %}

<div class="headingblock">
    <div class="headingleftbox">
        <h4>Showcase</h4>
    </div>
    <div class="headingmidbox">
        <h3>OneShot</h3>
    </div>
    <div class="headingrightbox">
        <h4>Showcase</h4>
    </div>
</div>

<div class="stage">
    <div class="stage2">
        <div class="stage3">
            <div class="mainbox">
                <div class="contentblock">
                    <div class="contentblocka">
                        <div class="carbox">
                            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                </div>
                                <div class="carousel-inner">
                                <div class="carousel-item active" data-bs-interval="6000" style="background-image: url(static/images/osingame1.jpg)">
                                    <img src="static/images/osingame1.jpg" class="d-block w-100" alt="oneshot">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/osingame2.jpg)">
                                    <img src="static/images/osingame2.jpg" class="d-block w-100" alt="oneshot">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/osmeta.jpg)">
                                    <img src="static/images/osmeta.jpg" class="d-block w-100" alt="oneshot">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="contentblockb">
                        <p class="para"><br>This puzzle adventure game was developed in 2014 for a developer competition. After receiving good feedback the original game was expanded for a more complete experience in 2016. It is currently due to be ported to Switch, PS4 and XboxOne. It was nominated for the "PC Game of the Year" Golden Joystick Award in 2017.<br>This was a genuinly touching experience, I was hooked from the start and was constantly suprised along the journey. This is one that stays with you after you finish it.
                        </p>
                    </div>
                </div>

                <div class="contentblock2">
                    <div class="contentblock2a">
                            <img class="lowerpic2" src="static/images/oslogotall.jpg">
                    </div>
                    <div class="contentblock2b">
                        <ul class="list">
                            <bold>Gameplay Loop:</bold>Explore, story, puzzles
                            <bold>Gameplay Time:</bold>4-10 hours
                            <bold>Pros:</bold>Impactful narrative, good soundtrack, atmosphere, unique mechanics, meta.
                            <bold>Considerations:</bold>Play in a dimly lit area with headphones for maximum atmosphere. Do not research this game, go in totally blind. Trust us!
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/index3.html
{% extends 'base.html' %}
{% block content %}

<div class="headingblock">
    <div class="headingleftbox">
        <h4>Recommended</h4>
    </div>
    <div class="headingmidbox">
        <h3>The Binding of Isaac : Repentence</h3>
    </div>
    <div class="headingrightbox">
        <h4>Recommended</h4>
    </div>
</div>

<div class="stage">
    <div class="stage2">
        <div class="stage3">
            <div class="mainbox">
                <div class="contentblock">
                    <div class="contentblocka">
                        <div class="carbox">
                            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                </div>
                                <div class="carousel-inner">
                                <div class="carousel-item active" data-bs-interval="6000" style="background-image: url(static/images/isaacingame.jpg)">
                                    <img src="static/images/isaacingame.jpg" class="d-block w-100" alt="isaac">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/isaacingame2.jpg)">
                                    <img src="static/images/isaacingame2.jpg" class="d-block w-100" alt="isaac">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/isaacingame5.jpg)">
                                    <img src="static/images/isaacingame5.jpg" class="d-block w-100" alt="isaac">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="contentblockb">
                        <p class="para"><br>Originally released in 2011 by Super Meat Boy developer Edmund McMillen, The Binding of Isaac is rightly considered a classic by fans of rogue-likes and many others. It is based on the Biblical story the same name, which has allowed for a fascinating direction in the games design. Mechanics, environments, characters and items all relate to this theme.<br>The game has recieved multiple expansions and updates since the intial release with the most recent (and final) 'Repentence' releasing last year. Intruiging story, fantastic mechanics and potentially hundreds of hours of gameplay included.</p>
                    </div>
                </div>

                <div class="contentblock2">
                    <div class="contentblock2a">
                            <img class="lowerpic3" src="static/images/isaacpostertall.jpg">
                    </div>
                    <div class="contentblock2b">
                        <ul class="list">
                            <bold>Genre:</bold>Rogue-like, Procedural, Action-adventure
                            <bold>Gameplay Loop:</bold>Combat, character builds, bosses
                            <bold>Gameplay Time:</bold>1 - 1000 hours
                            <bold>Pros:</bold>Rogue-like, interesting theme, endless builds, branching paths, hundreds of items, unlocks/challenges/achievements
                            <bold>Considerations:</bold>Addiction Warning!! If this game clicks with you, you are going to be in a relationship with it. Love AND hate will is innevitable..
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/index4.html
{% extends 'base.html' %}
{% block content %}

<div class="headingblock">
    <div class="headingleftbox">
        <h4>Your Pick!</h4>
    </div>
    <div class="headingmidbox">
        <h3>Axiom Verge</h3>
    </div>
    <div class="headingrightbox">
        <h4>Your Pick!</h4>
    </div>
</div>

<div class="stage">
    <div class="stage2">
        <div class="stage3">
            <div class="mainbox">
                <div class="contentblock">
                    <div class="contentblocka">
                        <div class="carbox">
                            <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                                </div>
                                <div class="carousel-inner">
                                <div class="carousel-item active" data-bs-interval="6000" style="background-image: url(static/images/axiomingame4.jpg)">
                                    <img src="static/images/axiomingame4.jpg" class="d-block w-100" alt="axiomverge">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/axiomingame5.jpg)">
                                    <img src="static/images/axiomingame5.jpg" class="d-block w-100" alt="axiomverge">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                <div class="carousel-item" data-bs-interval="6000" style="background-image: url(static/images/axiomingame3.jpg)">
                                    <img src="static/images/axiomingame3.jpg" class="d-block w-100" alt="axiomverge">
                                    <div class="carousel-caption d-none d-md-block">
                                    <h5></h5>
                                    <p></p>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="contentblockb">
                        <p class="para"><br>Considered a love letter to classic games, Axiom Verge puts the S in SNES. It celebrates the retro shooters of the 90's while injecting shots of adrenaline into all design areas. Super Metroid gave you a two weapons? Well Axiom Verge gives you 10. Plus fun items and mechanics that makes you think, 'why didn't someone do this before?'<br><br>You play as Trace the scientist and find yourself in a mysterious room, in a mysterious world, hearing a mysterious voice. You're a fish in a barrel...but you have a massive gun...and you're going to find out what the hells going on.
                        </p>
                    </div>
                </div>

                <div class="contentblock2">
                    <div class="contentblock2a">
                            <img class="lowerpic4" src="static/images/axiom.gif">
                    </div>
                    <div class="contentblock2b">
                        <ul class="list">
                            <bold>Genre:</bold>Retro, Metroidvania, Action-adventure
                            <bold>Gameplay Loop:</bold>Combat, Exploration, Bosses
                            <bold>Gameplay Time:</bold>10 - 16 hours
                            <bold>Pros:</bold>Interesting theme/story, great soundtrack, weapon variety, unique mechanics
                            <bold>Considerations:</bold>Turn it up!!!
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/index5.html
{% extends 'base.html' %}
{% block content %}

<div class="headingblock">
    <div class="headingleftbox">
        <h4>Contact</h4>
    </div>
    <div class="headingmidbox">
        <h4>Contact</h3>
    </div>
    <div class="headingrightbox">
        <h4>Contact</h4>
    </div>
</div>

<div class="stage">
    <div class="stage2">
        <div class="stage3">
            <div class="mainbox">
                <div class="contentblock">
                    <div class="contentblocka">
                        <img class="lowerpic5" src="static/images/delta1.jpg">
                    </div>
                    <div class="contentblockb">
                        <p class="para"><br>Thank you for visiting our humble site. Please feel free to contact us with any questions or feedback. Get invloved! Vote in our weekly poll so you're favourite game can be shared with others.<br><br>marcusjolmes191@gmail.com</p>
                        
                    </div>
                </div>

                <div class="contentblock2">
                    <div class="contentblock2a">
                        <img class="lowerpic6" src="static/images/oslogotall.jpg">
                    </div>
                    <div class="contentblock2b">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}